### ISSUE TITLE
1.1 Changelog

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/UHC#60]
### New Features
- `TheEnd` module for disabling travelling to the end
- `HorseHealing` module for disabling horse healing
- `/permaday` command for disabling time and setting the sun to above
- `/uhc status` shows the status of the modules without opening the inventory, can be used via CLI
- Modules can have their inventory 'weighting' modified via the config file to change the ordering
- 'Spacer' items can be added to the uhc inventory at specified weights
- Lore for golden heads can be modified via messages.conf (remove the player name to get stackable heads) 
- Team requests can be configured to automatically whitelist members on accept
- `/h` command has extra flags to set the health/max health of players
- Support for using the boss bar instead of action bar in `/timer`. Boss bar requires 1.9+, action bar requires ProtocolLib to be installed. If neither are satisfied the timer will not load. 
### Enhancements
- Lore for modules can now be edited via multiple lines in messages.conf
- Health updates in the scoreboard objectives are now more responsive in healing/taking damage
### Fixes
- Fixed a couple incorrect messages.conf keys breaking a couple of commands
- Fixed issue relating to starting the plugin with a disabled team module
- Improved compatibility with multiworld plugins in nether and end modules
- Fixed world border taking the radius as the diameter
### API
- Module/DisableableModule/ModuleRegistry API changes

**If you are using [FancyFreeze](https://github.com/Eluinhost/FancyFreeze) you must update it to 1.1.0 also to maintain compatability with this version**

**Comment by Eluinhost** [comment]
@D4mnX is there anything else you want included in this version or is it good to go after #72

**Comment by ghost** [comment]
As for small stuff, there are 2 things that might be useful for hosts that could reasonably make 1.1 in time:
- Basic health management - most UHC hosts use [Skript](https://github.com/Njol/Skript) for that but having it in the plugin itself might be helpful for hosts willing to migrate from the dreaded dev15. (EDIT: #73)
- Loading/saving full player backups on demand / on player death. For public UHC games it's an useful tool to check if a player has died to a glitch. This could be implemented by reusing code from the player reset module. (EDIT: #74)
- EDIT: I forgot to mention, PercentHealth doesn't update on onHeal. Should be a pretty simple fix. (EDIT: #75)

Health management is trivial to implement (could even be one command with -m flag for max health), player backups on the other hand feel like something that could really mess things up if there's even the smallest bug. I personally use [a skript](https://gist.github.com/D4mnX/16f534d3f0f3a46781711c75e0c22cfc) for it but it's basically a bodge.

I have some interesting ideas for 1.2 but that's out of the scope here.

**Comment by Eluinhost** [comment]
OK, I think this is all good to go now. I'll have to take some time tomorrow to make draw up a proper changelog and make sure everything is included. @D4mnX if you think of anything in the meantime drop me a pm in skype
