### ISSUE TITLE
[Info] Why using ProtocolLib for ActionBar ?

### ISSUE THREAD

**Issue by TheTonyk** [Eluinhost/UHC#69]
Hi,

I'm not very good in Java bur why using ProtocolLib instead of NMS to display messages on the ActionBar ?

Thanks !

**Comment by Eluinhost** [comment]
Does the NMS version not just hook in to send a packet anyway? I'd prefer to use ProtocolLib for anything packet related

**Comment by TheTonyk** [comment]
Okay, thanks !
