### ISSUE TITLE
Wrong PluginDisableEvent imported in BossBarRenderer

### ISSUE THREAD

**Issue by ghost** [Eluinhost/UHC#95]
This causes bossbar display to reset whenever any OTHER plugin than UHC is reloaded.

Fix PR coming in a few minutes.

**Comment by Eluinhost** [comment]
Woops, is this event only used for the boss bar? itll be worth renaming it
then. Was this in 1.1.0 release? We'll need to also create branch
releases/1.0 and put a fix out as 1.0.1

**Comment by ghost** [comment]
Yeah, the event was only used by the bossbar (included in 1.1.0, not in 1.0.0), I don't think this needs a hotfix as this will only result in glitches during hot plugin reloads. (EDIT: Caused by plugins like PlugMan)

**Comment by Eluinhost** [comment]
yeah I meant 1.1.1, it won't hurt to backport the fix so people don't have to wait for 1.2.0, I'll create it now

**Comment by Eluinhost** [comment]
Dropped as https://github.com/Eluinhost/UHC/commit/fff33e23cb75c51e76372d8da788e1619b90cbfb and https://github.com/Eluinhost/UHC/releases/tag/1.1.1 in releases/1.1.x
